
1. load the dataset using pandas and view the first two rows of the dataset. You want to know how many rows and columns are in the DataFrame; write a code to check the number of rows and columns.

In [1]:

import pandas as pd
import numpy as np

df = pd.read_csv('Datasets_50_Days_Of_Data_Analysis/runners_and_income_data.csv')
df.head(2)

   Name  Miles Run  Time in hrs   Age   Income Gender
0   Joe       45.0         40.0  23.0  50000.0   male
1  Phil        NaN         38.0  44.0      NaN   male

In [2]:

print("The number of rows: ", df.shape[0])
print("The number of columns: ", df.shape[1])

The number of rows:  23
The number of columns:  6


2. Write a code to check how many NaN values are in the DataFrame. Drop rows that have all NaN values. Replace the remaining NaN values with the value 00.0 (use pandas).

In [3]:

print("Number of NaN values: ", df.isna().sum().sum())

Number of NaN values:  50

In [4]:
df.dropna(axis = 0, how = 'all', inplace = True)

In [5]:
df.fillna(value= 00.0, inplace = True)

In [6]:

print("Number of NaN values: ", df.isna().sum().sum())

Number of NaN values:  0

In [7]:
df.head()

   Name  Miles Run  Time in hrs   Age   Income  Gender
0   Joe       45.0         40.0  23.0  50000.0    male
1  Phil        0.0         38.0  44.0      0.0    male
2   Ken       63.0          0.0  56.0  60000.0  female
3   Jos       36.0         50.0   0.0  75000.0    male
4  Luke       43.0         50.0  34.0      0.0  female


3. What does the describe() method do? Use describe to return the mean of the "Miles Run" column.

In [8]:
df.describe()["Miles Run"]["mean"]

np.float64(29.470588235294116)

4. Using the np.sum, what is the total miles run by all the names in the DataFrame.

In [9]:

print("Total miles run: ", np.sum(df["Miles Run"]))

Total miles run:  501.0


5. How many people have an income of $50000? Return a list of names.

In [10]:
names_of_5000_income = df.query("Income== 50000").iloc[0:,0]
print(list(names_of_5000_income))

['Joe', 'Teddy', 'Ira']


6. Create a subset of the DataFrame by selecting the last two rows of the dataset. Reset the index and drop the other index column. Save the DataFrame to csv. Name your subset as "runners_data_modified.csv". Save it without the index.

In [11]:

# Accessing the last two rows of the DataFrame
df2 = df.tail(2)
# Reset the index
df2.reset_index(inplace=True, drop= True)
df2

       Name  Miles Run  Time in hrs   Age   Income Gender
0    Barack       35.0         40.0  62.0  33000.0   male
1  Vladamir       44.0         38.0  64.0  53000.0   male

In [12]:

df2.to_csv("runners_data_modified.csv", index=False)